development:
  pics_mail_host:
  pics_mail_port:
  pics_mail_ssl:
  pics_mail_address:
  pics_mail_pass:
  pics_authorized_emails:
    - email_1@email.com
    - email_2@email.com
    - email_3@email.com


test:

production: