test:
  host: 'http://dbjohn.com/'
  domain: yourdomain.com

  cap_applicationdir: /home/../..
  cap_user: someuser

  devise_secret_key: "generate with rake secret"
  secret_token: "generate with rake secret"

  admin_email: your@email.com

  textcaptcha_api_key: demo

  pics_mail_host: mail.webfaction.com
  pics_mail_port: 110
  pics_mail_ssl: false
  pics_mail_address: userid
  pics_mail_pass: pass
  pics_authorized_emails:
    - email1@email.com
    - email2@email.com

  smtp_server: smtp.webfaction.com
  smtp_port: 587

  analytics_key: 12345

  git_repo: git@github.com:user/repo.git

  disqus_shortname:

  # https://www.google.com/cse
  google_search_key:

development:
  host: 'http://dbjohn.com/'
  domain: yourdomain.com

  cap_applicationdir: /home/../..
  cap_user: someuser

  devise_secret_key: "generate with rake secret"
  secret_token: "generate with rake secret"

  admin_email: your@email.com

  textcaptcha_api_key: demo

  pics_mail_host: mail.webfaction.com
  pics_mail_port: 110
  pics_mail_ssl: false
  pics_mail_address: userid
  pics_mail_pass: pass
  pics_authorized_emails:
    - email1@email.com
    - email2@email.com

  smtp_server: smtp.webfaction.com
  smtp_port: 587

  analytics_key: 12345

  git_repo: git@github.com:user/repo.git

  disqus_shortname:

  # https://www.google.com/cse
  google_search_key:

production:
  host: 'http://dbjohn.com/'
  domain: yourdomain.com

  cap_applicationdir: /home/../..
  cap_user: someuser

  devise_secret_key: "generate with rake secret"
  secret_token: "generate with rake secret"

  admin_email: your@email.com

  textcaptcha_api_key: demo

  pics_mail_host: mail.webfaction.com
  pics_mail_port: 110
  pics_mail_ssl: false
  pics_mail_address: userid
  pics_mail_pass: pass
  pics_authorized_emails:
    - email1@email.com
    - email2@email.com

  smtp_server: smtp.webfaction.com
  smtp_port: 587

  analytics_key: 12345

  git_repo: git@github.com:user/repo.git

  disqus_shortname:

  # https://www.google.com/cse
  google_search_key:
