development:
  pics_mail_host: mail.webfaction.com
  pics_mail_port: 110
  pics_mail_ssl: false
  pics_mail_address: pics2104@dbjohn.com
  pics_mail_pass: pics_password
  pics_authorized_emails:
    - dj@dbjohn.com
    - djohn@archdiocese-no.org
    - djohn@arch-no.org'

test:

production: