test:
  cap_applicationdir:
  cap_user:
  devise_secret_key:
  secret_token:
  admin_email: email@email.com
  textcaptcha_api_key: demo

  pics_mail_host: mail.webfaction.com
  pics_mail_port: 110
  pics_mail_ssl: false
  pics_mail_address:
  pics_mail_pass:
  pics_authorized_emails:
    - email1@email.com
    - email2@email.com

  smtp_server: smtp.webfaction.com
  smtp_port: 587
  smtp_domain:

development:
  cap_applicationdir:
  cap_user:
  devise_secret_key:
  secret_token:
  admin_email: email@email.com
  textcaptcha_api_key: demo

  pics_mail_host: mail.webfaction.com
  pics_mail_port: 110
  pics_mail_ssl: false
  pics_mail_address:
  pics_mail_pass:
  pics_authorized_emails:
    - email1@email.com
    - email2@email.com

  smtp_server: smtp.webfaction.com
  smtp_port: 587
  smtp_domain:
production:
  cap_applicationdir:
  cap_user:
  devise_secret_key:
  secret_token:
  admin_email: email@email.com
  textcaptcha_api_key: demo

  pics_mail_host: mail.webfaction.com
  pics_mail_port: 110
  pics_mail_ssl: false
  pics_mail_address:
  pics_mail_pass:
  pics_authorized_emails:
    - email1@email.com
    - email2@email.com

  smtp_server: smtp.webfaction.com
  smtp_port: 587
  smtp_domain: